### ISSUE TITLE
Custom jinja/liquid templates

### ISSUE THREAD

**Issue by vahidzee** [webifier/build#3]
Sections can specify custom templates to alter how they want their information to be rendered. For example, the following template.

```html
# jinja/liquid template.html
<h1>{{name}}</h1>
<h2>{{role}}</h2>
```
can be specified to process information of a person like:
```yaml
section-key:
    template: template.html
    name: Some Name
    role: Some Role
```
By specifying `template-kind` to be either `jinja2` or `liquid` we can support both of these common templating tools without compromise. And by setting `template-apply` to be either `whole`, `value`, one can change how the template should be applied to the information, whether to be applied to each value or to encapsulate all of the information.
